example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('wishlist/ajax', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, show_ajax, submit_barang
from wishlist.views import show_xml 
from wishlist.views import show_json
from wishlist.views import show_json_by_id 
from wishlist.views import show_xml_by_id
from wishlist.views import register 
from wishlist.views import login_user 
from wishlist.views import logout_user 


app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_ajax, name='show_ajax'),
    path('ajax/submit/', submit_barang, name='submit_barang'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Bella',
        'last_login': request.COOKIES.get('last_login'),
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/ajax/')
def show_ajax(request):
    # data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        # 'list_barang': data_barang_wishlist,
        'nama': 'Bella',
        'last_login': request.COOKIES.get('last_login'),
    }
    return render(request, "wishlist_ajax.html", context)


def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

def submit_barang(request):
    if request.method == 'POST':
        nama = request.POST.get("nama_barang")
        harga = request.POST.get("harga_barang")
        deskripsi = request.POST.get("deskripsi")
        barang = BarangWishlist(nama_barang=nama, harga_barang=harga, deskripsi=deskripsi)                                    
        barang.save()
    return redirect('wishlist:show_ajax')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login" style="width: 300px; height: 300px; margin: auto; margin-top: 170px;" >
    <div style="margin-bottom: 30px">
        <h1 class="text-center">Login</h1>
    </div>
    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            
        </table>
        <tr>
            <td><input class="btn login_btn btn-secondary" type="submit" value="Login" style="margin-left:120px; margin-top: 20px; margin-bottom: 20px; border-radius: 12px;"></td>
        </tr>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
    .button {
      background-color: #b3270f; 
      border: none;
      color: white;
      padding: 7px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 1px 1px;
      cursor: pointer;
    }
    

    .button4 {border-radius: 12px;}
    
    </style>
    </head>

<nav class="navbar navbar-dark bg-dark">
<div class="container-fluid">
    <span class="navbar-brand mb-0 h1">{{nama}}</span>
    <div class="rounded-4">
    <button type="button" class="button button4 "><a href="{% url 'wishlist:logout' %}" class="text-white">Logout</a></button>
    </div>
</div>
</nav>


<div class="m-5">
    <table class="table table-bordered" >
        <tr class="table-primary">
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
    {% endfor %}
    </table>
    <div class="m-5">
        <p class="text-center fs-6" >Sesi terakhir login: {{ last_login }}</p>
    </div>
    
</div>
{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
    .button {
      background-color: #b3270f; 
      border: none;
      color: white;
      padding: 7px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 1px 1px;
      cursor: pointer;
    }

    .button4 {border-radius: 12px;}
    
    </style>
</head>

<!-- navbar -->
<nav class="navbar navbar-dark bg-dark">
<div class="container-fluid">
    <span class="navbar-brand mb-0 h1">{{nama}}</span>
    <div class="rounded-4">
    <button type="button" class="button button4 "><a href="{% url 'wishlist:logout' %}" class="text-white">Logout</a></button>
    </div>
</div>
</nav>

<!-- table header -->
<div class="m-5">
    <table class="table table-bordered content" >
        <tr class="table-primary">
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
        </tr>
    </table>

    <div class="m-5">
        <p class="text-center fs-6" >Sesi terakhir login: {{ last_login }}</p>
    </div>  
</div>

<!-- form new wishlist -->
<form method="POST" action="">
    {% csrf_token %}
    <div class="card-body">
        <div class="m-2" style="display:flex; flex-direction: column; text-align: left;">
            <label for="judul"> Nama Barang: </label>
            <input id="nama" type="text" name="nama" placeholder="Nama barang " required>
        </div>
        <div class="m-2" style="display:flex; flex-direction: column; text-align: left;">
            <label for="deskripsi"> Harga Barang: </label>
            <input id="harga" type="text" name="harga" placeholder="Harga barang" required>
        </div>
        <div class="m-2" style="display:flex; flex-direction: column; text-align: left;">
            <label for="deskripsi">Deskripsi: </label>
            <input id="deskripsi" type="text" name="deskripsi" placeholder="Deskripsi" required>
        </div>
    </div>

    <center><input class="button button4" type="submit" value="Tambah barang" style="background-color: #1c54cc;"></center>
</form>

<!-- ajax script -->
<script>
    $(document).ready(function () {

        // FETCHING DATA FROM JSON FILE
        $.getJSON( "{% url 'wishlist:show_json' %}", function (data) {
            var barang = '';

            // ITERATING THROUGH OBJECTS
            $.each(data, function (key, value) {

                //CONSTRUCTION OF ROWS HAVING
                // DATA FROM JSON OBJECT
                barang += '<tr>';

                barang += '<td>' + value.fields.nama_barang + '</td>';

                barang += '<td>' + value.fields.harga_barang + '</td>';

                barang += '<td>' + value.fields.deskripsi + '</td>';

                barang += '</tr>';
            });
              
            //INSERTING ROWS INTO TABLE 
            $('table').append(barang);
        });
    });
</script>


 <script>
    $(document).ready(function () {
        $(".button").click(function(){
            let nama = $("#nama").val();
            let harga = $("#harga").val();
            let deskripsi = $("#deskripsi").val();
            let csrf_token = $("input[name='csrfmiddlewaretoken']").val();
            $.post('/wishlist/ajax/submit/', {
                nama_barang : nama,
                harga_barang : harga,
                deskripsi : deskripsi,
                csrfmiddlewaretoken: csrf_token,
            })
        })
    })
 </script>
{% endblock content %}